/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;


public class VentanaPrincipal extends javax.swing.JFrame {

    
    public VentanaPrincipal() {
    initComponents();

    DefaultListModel<String> modelo = new DefaultListModel<>();
    for (String tecnico : GestorDatos.listaTecnicos) {
        modelo.addElement(tecnico);
    }
    listTecnicos.setModel(modelo);

    actualizarListaClientes();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        panelEstados = new javax.swing.JTabbedPane();
        panelClientes = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtRazonSocial = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtRUC = new javax.swing.JTextField();
        btnRegistrarCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelInstalaciones = new javax.swing.JPanel();
        comboClientes = new javax.swing.JComboBox<>();
        txtDireccion1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTecnicos = new javax.swing.JList<>();
        comboTipo = new javax.swing.JComboBox<>();
        SpinnerFecha = new javax.swing.JSpinner();
        SpinnerHora = new javax.swing.JSpinner();
        btnRegistroInstalacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registros");
        setResizable(false);
        getContentPane().setLayout(null);

        panelClientes.setLayout(null);

        txtNombre.setBackground(new java.awt.Color(216, 216, 216));
        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre Completo"));
        panelClientes.add(txtNombre);
        txtNombre.setBounds(180, 60, 510, 60);

        txtRazonSocial.setBackground(new java.awt.Color(216, 216, 216));
        txtRazonSocial.setBorder(javax.swing.BorderFactory.createTitledBorder("Razón Social "));
        panelClientes.add(txtRazonSocial);
        txtRazonSocial.setBounds(180, 140, 270, 60);

        txtDireccion.setBackground(new java.awt.Color(216, 216, 216));
        txtDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Dirección"));
        panelClientes.add(txtDireccion);
        txtDireccion.setBounds(180, 290, 270, 70);

        txtTelefono.setBackground(new java.awt.Color(216, 216, 216));
        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefono"));
        panelClientes.add(txtTelefono);
        txtTelefono.setBounds(470, 220, 220, 60);

        txtCorreo.setBackground(new java.awt.Color(216, 216, 216));
        txtCorreo.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo"));
        panelClientes.add(txtCorreo);
        txtCorreo.setBounds(470, 140, 220, 60);

        txtRUC.setBackground(new java.awt.Color(216, 216, 216));
        txtRUC.setBorder(javax.swing.BorderFactory.createTitledBorder("RUC"));
        panelClientes.add(txtRUC);
        txtRUC.setBounds(180, 220, 270, 60);

        btnRegistrarCliente.setBackground(new java.awt.Color(101, 101, 255));
        btnRegistrarCliente.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        panelClientes.add(btnRegistrarCliente);
        btnRegistrarCliente.setBounds(50, 380, 150, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/señor.png"))); // NOI18N
        panelClientes.add(jLabel3);
        jLabel3.setBounds(60, 50, 300, 310);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Captura_de_pantalla_2025-06-15_021647-removebg-preview.png"))); // NOI18N
        panelClientes.add(jLabel5);
        jLabel5.setBounds(530, 350, 170, 90);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/f0ecf891abf60efa12d9bced9767247b.png"))); // NOI18N
        panelClientes.add(jLabel8);
        jLabel8.setBounds(10, 0, 720, 470);

        panelEstados.addTab("Registrar Cliente", panelClientes);

        panelInstalaciones.setLayout(null);

        comboClientes.setBackground(new java.awt.Color(216, 216, 216));
        comboClientes.setEditable(true);
        comboClientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));
        panelInstalaciones.add(comboClientes);
        comboClientes.setBounds(50, 30, 490, 70);

        txtDireccion1.setBackground(new java.awt.Color(216, 216, 216));
        txtDireccion1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dirección"));
        panelInstalaciones.add(txtDireccion1);
        txtDireccion1.setBounds(50, 300, 490, 70);

        listTecnicos.setBackground(new java.awt.Color(216, 216, 216));
        listTecnicos.setBorder(javax.swing.BorderFactory.createTitledBorder("Tecnicos"));
        listTecnicos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Carlos  Rodriguez", "Laura Sanchez", "Mario Torres" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listTecnicos);

        panelInstalaciones.add(jScrollPane2);
        jScrollPane2.setBounds(50, 190, 250, 100);

        comboTipo.setBackground(new java.awt.Color(216, 216, 216));
        comboTipo.setEditable(true);
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Servicios Electricos", "Aire Acondicionado ", "Alarma Contra Incendios", "Sistema de Ventilación" }));
        comboTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Instalación"));
        panelInstalaciones.add(comboTipo);
        comboTipo.setBounds(50, 110, 290, 70);

        SpinnerFecha.setModel(new javax.swing.SpinnerDateModel());
        SpinnerFecha.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha"));
        SpinnerFecha.setEditor(new javax.swing.JSpinner.DateEditor(SpinnerFecha, "dd/MM/yyyy "));
        panelInstalaciones.add(SpinnerFecha);
        SpinnerFecha.setBounds(350, 110, 190, 70);

        SpinnerHora.setModel(new javax.swing.SpinnerDateModel());
        SpinnerHora.setBorder(javax.swing.BorderFactory.createTitledBorder("Hora"));
        SpinnerHora.setEditor(new javax.swing.JSpinner.DateEditor(SpinnerHora, "HH:mm"));
        panelInstalaciones.add(SpinnerHora);
        SpinnerHora.setBounds(380, 200, 160, 80);

        btnRegistroInstalacion.setBackground(new java.awt.Color(101, 101, 255));
        btnRegistroInstalacion.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        btnRegistroInstalacion.setText("Registrar Instalación");
        btnRegistroInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroInstalacionActionPerformed(evt);
            }
        });
        panelInstalaciones.add(btnRegistroInstalacion);
        btnRegistroInstalacion.setBounds(550, 370, 150, 60);
        panelInstalaciones.add(jLabel1);
        jLabel1.setBounds(550, 180, 0, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Captura-de-pantalla-2025-06-15-021647 (1).png"))); // NOI18N
        panelInstalaciones.add(jLabel2);
        jLabel2.setBounds(580, 10, 120, 350);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Captura_de_pantalla_2025-06-15_021647-removebg-preview.png"))); // NOI18N
        panelInstalaciones.add(jLabel4);
        jLabel4.setBounds(40, 380, 140, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/f0ecf891abf60efa12d9bced9767247b.png"))); // NOI18N
        panelInstalaciones.add(jLabel7);
        jLabel7.setBounds(10, -120, 730, 710);

        panelEstados.addTab("Instalación", panelInstalaciones);

        getContentPane().add(panelEstados);
        panelEstados.setBounds(0, 0, 780, 540);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Captura de pantalla 2025-05-20 232208.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-20, -20, 880, 400);

        setSize(new java.awt.Dimension(756, 542));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarListaClientes(){
        comboClientes.removeAllItems();
for (Cliente c : GestorDatos.listaClientes) {
    ((javax.swing.JComboBox)comboClientes).addItem(c);
}
    }

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText().trim();
        String razonSocial = txtRazonSocial.getText().trim();
        String direccion = txtDireccion.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String correo = txtCorreo.getText().trim();
        String ruc = txtRUC.getText().trim();

        if (nombre.isEmpty() || razonSocial.isEmpty() || direccion.isEmpty() ||
        telefono.isEmpty() || correo.isEmpty() || ruc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos obligatorios.");
            return;
        }

        Cliente cliente = new Cliente(nombre, razonSocial, direccion, telefono, correo, ruc);
        GestorDatos.agregarCliente(cliente);
        JOptionPane.showMessageDialog(this, "Cliente registrado correctamente.");
        actualizarListaClientes();
        // Limpiar campos
        txtNombre.setText("");
        txtRazonSocial.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtRUC.setText("");
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnRegistroInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroInstalacionActionPerformed
        // TODO add your handling code here:
        Cliente clienteSeleccionado = (Cliente) comboClientes.getSelectedItem();
        String tipo = (String) comboTipo.getSelectedItem();
        Date fecha = (Date) SpinnerFecha.getValue(); 
        String hora = new SimpleDateFormat("HH:mm").format((Date) SpinnerHora.getValue()); 
        String direccion = txtDireccion1.getText().trim();
    
        List<String> tecnicosSeleccionados = listTecnicos.getSelectedValuesList();
    
        if (clienteSeleccionado == null || tipo.isEmpty() || fecha == null || hora.isEmpty() || direccion.isEmpty() || tecnicosSeleccionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos");
            return;
        }
    
        String fechaString = new SimpleDateFormat("dd/MM/yyyy").format(fecha);
        Instalacion instalacion = new Instalacion(clienteSeleccionado, tipo, fechaString, hora, direccion, tecnicosSeleccionados);
        GestorDatos.agregarInstalacion(instalacion);
        JOptionPane.showMessageDialog(this, "Instalación registrada con estado Pendiente");
    
       // para limpiar campos
       comboTipo.setSelectedItem("");
       SpinnerFecha.setValue(new Date()); // Reiniciar el JSpinner de fecha
       SpinnerHora.setValue(new Date()); // Reiniciar el JSpinner de hora
       txtDireccion1.setText("");
       listTecnicos.clearSelection();

    }//GEN-LAST:event_btnRegistroInstalacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinnerFecha;
    private javax.swing.JSpinner SpinnerHora;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnRegistroInstalacion;
    private javax.swing.JComboBox<String> comboClientes;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listTecnicos;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JTabbedPane panelEstados;
    private javax.swing.JPanel panelInstalaciones;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccion1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
